// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Patients.Data;

#nullable disable

namespace Patients.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260907150852_AdresseEtTelephoneNullable")]
    partial class AdresseEtTelephoneNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Patients.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateDeNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresse = "1 Brookside St",
                            DateDeNaissance = new DateTime(1966, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "F",
                            Nom = "TestNone",
                            Prenom = "Test",
                            Telephone = "100-222-3333"
                        },
                        new
                        {
                            Id = 2,
                            Adresse = "2 High St",
                            DateDeNaissance = new DateTime(1945, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "M",
                            Nom = "TestBorderline",
                            Prenom = "Test",
                            Telephone = "200-333-4444"
                        },
                        new
                        {
                            Id = 3,
                            Adresse = "3 Club Road",
                            DateDeNaissance = new DateTime(2004, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "M",
                            Nom = "TestInDanger",
                            Prenom = "Test",
                            Telephone = "300-444-5555"
                        },
                        new
                        {
                            Id = 4,
                            Adresse = "4 Valley Dr",
                            DateDeNaissance = new DateTime(2002, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "F",
                            Nom = "TestEarlyOnset",
                            Prenom = "Test",
                            Telephone = "400-555-6666"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
